### ISSUE TITLE
Feedback Tom Hunter

### ISSUE THREAD

**Issue by TomHunter1** [w201rdada/portfolio-mpaluta#1]
This isn't the first time I've heard this idea, but it's valuable in the sense that proposing a formalized approach is something not often explored well. It's a thoughtful question, I think your next steps are likely to build the idea out with some proposed data sources, metics or methods of approach. I personally read this and think of an insurance company's mortality rates, or a metric like  avg. expected life time value of a human (pragmatic and utilitarian). 

I think all possible approaches end up hinging on the different ethical schools of thought, links and listed below, and the question ultimately might not be answered b/c even philosophers cannot agree on which is the right one. If that's an issue, maybe if you picked 2 or 3 and determined what the metrics might look like and differ, that could be a fun approach without getting too entangled about arguing which is the best. 

Good luck!

From wikipedia(https://en.wikipedia.org/wiki/Ethics):
 * Virtue ethics
    * Stoicism
    * Contemporary virtue ethics
* Hedonism
    * Cyrenaic hedonism
    * Epicureanism
* State consequentialism
* Consequentialism/teleology
    * Utilitarianism
* Deontology
* Pragmatic ethics
* Ethics of care
* Role ethics
* Anarchist ethics
* Postmodern ethics

**Comment by mpaluta** [comment]
I did some more research into the literature since you mentioned you had seen similar things (and I have seen some too). I think the thought experiment strategy already exists, so I tried to aim the scope more broadly at democratizing ethical data policy, diving into some details on a method of implementation on autonomous vehicles as a case study. I added quite a bit on collection, implementation, and drawbacks per your and others' feedback.

I deliberately tried to avoid any user-facing complex philosophy in my proposed system because the average citizen isn't interested in that (even if we are). I think binary thought experiments are pretty digestible for the average person. I do think the differing schools of thought are useful for the back-end evaluation metrics of user response.

I appreciate your feedback on this. I am going to mark it as closed for now.
