### ISSUE TITLE
Feedback - Ahana

### ISSUE THREAD

**Issue by ahananamburi** [w201rdada/portfolio-mpaluta#3]
I love how well the idea has been described. Great structure and clarity from intro to conclusion!

Given the futuristic nature of the idea, you could possibly describe underlying assumptions. If I have understood this right, it assumes the existence of an algorithm that predicts the precise amount of damage done in different scenarios of accidents. It might help provide some context\background to your solution.

It might be helpful to go beyond the ideology and describe the data science solution further. How do you ensure participation and the build up of a dataset? E.g Do you get every purchaser/ driver of a car to respond to these questions? Does the government create a predictive model that is consistently leveraged by all vehicle manufacturers?

**Comment by mpaluta** [comment]
I refocused the scope on the details of the data and the implementation. I highlighted a few methods of participation and building a dataset, as well as how to get this data to corporations. I didn't dive too far into the weeds of assumptions of futurism because I wanted to keep the conversation on the policy. I think the principles could apply to many future states regardless of how exactly they play out.

Thanks for the feedback. I'm going to close this for now.
